### PR TITLE
Updated jbox version to 2.3.1

### PR DESCRIPTION
**Pull request by wanbinkimoon**
Fixed memory leak in rope joint and other minor issue causing slow performance

### CODE REVIEW

**Comment by shiffman** [comment]
Oh, thank you for this! Have you tested all the examples? I will take a look soon!

**Comment by wanbinkimoon** [comment]
@shiffman Nop, sorry I just run my own project and was fine, but I'll test them and let you know :)

**Comment by wanbinkimoon** [comment]
@shiffman I tested the examples yesterday, everything is smooth and clean :)

**Comment by shiffman** [comment]
Ok, merging! I will test before I publish new version!

**Pull request merged**
